/**
 * Write the app's bundled treatment menu, Zennara App/constants/treatmentTaxonomy.ts.
 *
 * Source: utils/treatmentTaxonomy.js (categories, icons, conditions) and
 * data/treatmentCatalogue.js (which condition each treatment helps with). The app draws
 * this before GET /consultations/taxonomy answers — and relies on it entirely while the
 * live API is older than that endpoint. Re-run whenever either file changes.
 *
 *   node scripts/exportTreatmentTaxonomy.js
 */
const fs = require('fs');
const path = require('path');
const { CATEGORIES, CONDITIONS } = require('../utils/treatmentTaxonomy');
const { treatments } = require('../data/treatmentCatalogue');
const { normaliseConditions } = require('../utils/treatmentTaxonomy');

const target = path.join(__dirname, '..', '..', 'Zennara App', 'constants', 'treatmentTaxonomy.ts');
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const lines = [
  '/**',
  ' * The treatment menu, bundled.',
  ' *',
  ' * GENERATED by Backend/scripts/exportTreatmentTaxonomy.js from utils/treatmentTaxonomy.js and',
  ' * data/treatmentCatalogue.js — regenerate rather than editing. The server is the source of',
  ' * truth: GET /consultations/taxonomy sends the live menu (panel order, icons, counts). This copy',
  ' * is what the treatment tab draws before that answer arrives, and all it has if the live API is',
  ' * older than the endpoint. Counts are never bundled; they come from the treatments on sale.',
  ' */',
  '',
  'export interface TreatmentCategoryEntry {',
  '  name: string;',
  '  slug: string;',
  '  /** Key drawn by components/treatments/TreatmentCategoryIcon. */',
  '  icon: string;',
  '  order: number;',
  '}',
  '',
  'export interface TreatmentConditionEntry {',
  '  key: string;',
  '  name: string;',
  '  blurb: string;',
  '  order: number;',
  '}',
  '',
  'export const TREATMENT_CATEGORIES: TreatmentCategoryEntry[] = [',
  ...CATEGORIES.map((c) => `  { name: ${q(c.name)}, slug: ${q(c.key)}, icon: ${q(c.icon)}, order: ${c.order} },`),
  '];',
  '',
  'export const TREATMENT_CONDITIONS: TreatmentConditionEntry[] = [',
  ...CONDITIONS.map((c) => `  { key: ${q(c.key)}, name: ${q(c.name)}, blurb: ${q(c.blurb)}, order: ${c.order} },`),
  '];',
  '',
  '/** Conditions per treatment slug — used only for a treatment the server sends without `conditions`. */',
  'export const CONDITIONS_BY_TREATMENT: Record<string, string[]> = {',
  ...treatments.filter((t) => t.conditions.length).map((t) => `  ${q(t.slug)}: [${normaliseConditions(t.conditions).map(q).join(', ')}],`),
  '};',
  '',
];

fs.writeFileSync(target, lines.join('\n'));
console.log(`wrote ${path.relative(process.cwd(), target)} — ${CATEGORIES.length} categories, ${CONDITIONS.length} conditions, ${treatments.filter((t) => t.conditions.length).length} treatments with conditions`);
